# Generated by Django 3.2.9 on 2021-11-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('year', models.DateField(auto_now_add=True)),
                ('thumb', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('story', models.TextField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
